--liquibase formatted sql

--changeset scherbakov:1
CREATE TABLE socksInStocks(
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                              color varchar(20) NOT NULL,
                              cottonPart int NOT NULL,
                              quantity int NOT NULL
)